version: '3.9'
services:
    vmq-itchat:
        image: lyy0709/vmq-itchat:latest
        container_name: vmq-itchat
        volumes:
            - ${PWD}/config:/app/config
        ports:
            - 8000:8000
        restart: unless-stopped